 version: 2.1 

 orbs:
   aws-s3: circleci/aws-s3@2.0.0 # use the AWS S3 orb in your config

 workflows: # Define a Workflow running the build job, then the deploy job
   version: 2
   build-deploy: # Make a workflow to build and deploy your project
     jobs:
       - build

